name: Dart CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    container:
      image:  cirrusci/flutter
      
   
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: pub get
    - name: Run build apk
      run: flutter build apk
